# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketitems',
            options={'ordering': ['modified_on']},
        ),
    ]
