# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketitems',
            name='blist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.Bucketlist'),
        ),
    ]
