# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160120_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketlist',
            options={'ordering': ['-modified_on']},
        ),
    ]
